FROM node:10-alpine

WORKDIR /app/

COPY /edge/modules/MessageSimulatorModule/package*.json ./

RUN npm install --production

COPY /edge/modules/MessageSimulatorModule/*.js ./

COPY /messages/ ./messages/

EXPOSE 9228

USER node

CMD ["node", "--inspect=0.0.0.0:9228", "app.js"]
