FROM node:10-alpine

WORKDIR /app/edge/modules/CompressionModule/

COPY edge/modules/CompressionModule/package*.json ./

RUN npm install --production

COPY shared/*.js ../../../shared/

COPY /edge/modules/CompressionModule/*.js ./

EXPOSE 9229

USER node

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
