FROM node:10-alpine

COPY /shared /shared

COPY /edge/modules/CompressionNodeModule/package*.json /edge/modules/CompressionNodeModule/

WORKDIR /edge/modules/CompressionNodeModule/

RUN npm install --production

COPY /edge/modules/CompressionNodeModule/app.js /edge/modules/CompressionNodeModule/

EXPOSE 9229

USER node

CMD ["node", "--inspect=0.0.0.0:9229", "app.js"]
